_format_version: "3.0"
_transform: true

services:
  - name: task-service
    url: http://task-service:8000
    routes:
      - name: task-route
        paths:
          - /api
        strip_path: true 